// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7QKvm7_JmDYAYQyvgR524i7tZDeckbPM',
    appId: '1:854575645581:web:d0bc6bebd5920aabed33c4',
    messagingSenderId: '854575645581',
    projectId: 'test-project--0',
    authDomain: 'test-project--0.firebaseapp.com',
    storageBucket: 'test-project--0.appspot.com',
    measurementId: 'G-RCGL1WRJW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo6hkrq7dnjopI_luS6D40DUd7PoKKt_E',
    appId: '1:854575645581:android:c7ef85f636671c95ed33c4',
    messagingSenderId: '854575645581',
    projectId: 'test-project--0',
    storageBucket: 'test-project--0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMt7UMKQSXjreDuGlz2_AWTrsNH8XUvXs',
    appId: '1:854575645581:ios:396144655e6b6c5aed33c4',
    messagingSenderId: '854575645581',
    projectId: 'test-project--0',
    storageBucket: 'test-project--0.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMt7UMKQSXjreDuGlz2_AWTrsNH8XUvXs',
    appId: '1:854575645581:ios:396144655e6b6c5aed33c4',
    messagingSenderId: '854575645581',
    projectId: 'test-project--0',
    storageBucket: 'test-project--0.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7QKvm7_JmDYAYQyvgR524i7tZDeckbPM',
    appId: '1:854575645581:web:10c7141f06672cfaed33c4',
    messagingSenderId: '854575645581',
    projectId: 'test-project--0',
    authDomain: 'test-project--0.firebaseapp.com',
    storageBucket: 'test-project--0.appspot.com',
    measurementId: 'G-3XL3X7HX5Z',
  );
}
